site_name: My Docs

theme:
  name: material
  features:
    - content.action.view
    - content.action.edit
    - content.code.copy
    - navigation.tabs
    - navigation.path
  icon:
    repo: fontawesome/brands/github-alt






nav:
- Programming:
  - C++:
    - programming/cpp/effective-cpp.md
  - .NET:
    - Entity Framework: programming/efcore.md
  - Python:
    - PEP: programming/python/pep.md
    - Packaging: programming/python/packaging.md
    - GIL: programming/python/gil.md
    - Concurrent programming: programming/python/async.md
  - Code Review: programming/code-review.md
  - Cryptography: programming/cryptography.md
  - Containerization:
    - Docker: programming/docker.md
    - Kubernetes: programming/kubernetes.md
  - Linux: programming/linux.md
- Sciences:
  - Physics: science/physics.md

markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

repo_url: https://github.com/edouardberthe/doc
repo_name: edouardberthe/doc
edit_uri: edit/main/docs/