site_name: My Docs

theme: material

nav:
    - Programming:
        - Docker: docker.md
        - .Net:
            - Entity Framework: efcore.md
        - Kubernetes: kubernetes.md
        - Linux: linux.md
        - Python:
            - GIL: python/gil.md
            - Packaging: python/packaging.md
            - PEP: python/pep.md
        - Cryptography: cryptography.md
        - Code Review: code-review.md
    - Sciences:
        - Physics: physics.md

markdown_extensions:
    - toc:
        permalink: true
